export { createWorkspace } from '@tabula/tabula'
export type {
	Message,
	MessageType,
	TabMeta,
	StateEntry,
	StateClock,
	StateDeleteOperation,
	StateOperation,
	StateSetOperation,
	StateSyncRequestPayload,
	StateSyncResponsePayload,
	ViewClaimToken,
	ViewClaimResult,
	ViewRegistryEntry,
	WorkspaceOptions,
	ViewOpenOptions,
	ViewHandle,
	Workspace,
	WorkspaceState,
	WorkspaceViews,
	WorkspaceTabs,
	WorkspaceEventMap,
	ViewClaimedEvent,
	ViewVacantEvent,
	ViewConflictEvent,
	LeaderChangeEvent,
	MessageIdentity,
	MessageTarget,
	ProtocolIncompatibleEvent,
	ProtocolVersion,
	WorkspaceLifecycle,
	WorkspaceStatus,
	WorkspaceSyncState,
} from '@tabula/tabula'
export {
	CapabilityError,
	StorageCorruptionError,
	StorageOperationError,
	ViewAlreadyClaimedError,
	WorkspaceDestroyedError,
	WorkspaceFailedError,
} from '@tabula/tabula'
